### PR TITLE
Refactor heat.py into a subpackage

### PR DESCRIPTION
**Pull request by jzuhone**
## Description

`heat.py` currently contains all of the classes which model heating inputs. Currently, this file is quite bloated, containing all currently used classes, as well as some which are no longer used. 

This PR refactors this structure, while leaving the API intact, by changing `heat.py` into a `heat` subpackage. The files under `heat` are now:

* `base.py`: base heating classes
* `generic.py`: generic heating classes (this could be merged into the one above potentially)
* `solar.py`: all of the solar heating classes
* `earth.py`: the earthshine in the ACIS radiator FOV code
* `electronics.py`: heating from electronics boxes

I also put deprecated classes into a new file, `deprecated.py`, under the `component` subpackage.

This PR also:

* Removes the `DpaSolarHeat` copy of the `SolarHeatHrc` class
* Removes `from future import print_function` call at the top of `heat.py`

## Interface impacts

Since this is just code reorganization under the hood, but all imports from the xija API should be the same, there should be no interface impacts. 

### Unit tests

- [x] Mac

Independent check of unit tests by @taldcroft 
- [x] Mac

### Functional tests

`xija_gui_fit` and `acis_thermal_check` tests pass.

### CODE REVIEW

**Comment by taldcroft** [comment]
@jzuhone - I added a test we should have had long ago which runs every model in `chandra_models`. With this test in place I'm good with this PR once you do functional tests, without having really checked the refactor details.

**Comment by taldcroft** [comment]
@jzuhone - this is just waiting for those quick functional tests. Let's get this in then I can do the black format PR for xija. :smile:

**Comment by jzuhone** [comment]
Hi @taldcroft I ran the functional tests and all looks good.

**Review by taldcroft — APPROVED** [review]
Looks good!

**Pull request merged**
