### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by taldcroft**

### CODE REVIEW

**Comment by jzuhone** [comment]
I looked over the source, it seems like you may want to add `from __future__ import print_function` in a few more source files.

**Comment by taldcroft** [comment]
Thanks @jzuhone.  Those should all be of the form `print(one_thing)`, but I'll go ahead and do that anyway.

I hope you're psyched about Python 3.  I spent the week getting much of core Ska working on Py3 except using Py 3.5 because 3.6 isn't fully available in conda).

Next on my list is trying out the ACIS thermal checkers...

**Comment by jeanconn** [comment]
:+1: 

Only tested from the 2.18 environment.

**Comment by jzuhone** [comment]
@taldcroft do you think this PR needs anything else? or can we merge it?

**Comment by taldcroft** [comment]
Yikes, I had completely forgotten about this.  What's worse is that 3.7.1 is actually installed to flight Ska.  So this should indeed be merged, but I just need to double-check that this PR exactly corresponds to what is installed.  Standby.

**Comment by taldcroft** [comment]
OK, confirmed that the 3.7.1 version in /proj/sot/ska/pkgs/ (and Ska flight) is exactly this PR.

**Pull request merged**
