### PR TITLE
gui_fit upgrades

### PR DESCRIPTION
**Pull request by jzuhone**
This pull request contains a number of upgrades to `gui_fit`. It was initially demoed and discussed at the TWG on 11/25/19. 

Major highlights:

* Added the "histogram" plots from the dashboard as an option to the GUI, so they can be made and re-made in between model fits. 
* Added buttons for drawing radzones and limit lines to the plots. 
* Added an application icon. 
* The title bar now displays the JSON file which is being used and this is updated if one save the current model to a new filename. 
* Added an IPython terminal which has access to several commands related to fitting, freezing and thawing, and setting of parameters. 
* Added "ignore" and "notice" options to the command box and the IPython terminal which allows one to mask out certain times from the fit, and remove those masks later. 
* Added an optional interactive line which is synced between the plots and a table which shows the state at that line. 
* Added an interface for writing MSID, state, and model data to an ASCII table. 
* Added an interface for displaying model info, including the SHA256 sum of the model file. 
* Fixed the behavior of the "Stop" button on macOS.
* Fixed an issue where parameters would reset after a fit which ran out of iterations.
* Added functionality for adding limits to the JSON file.
* Added units to plots.
* Updated colors on plots.

I also fixed little UI issues here and there as I found them. 

A screenshot attempting to show most of these features:

image

Needs
 - [x] rebase or other fix of merge conflicts
 - [x] confirmed testing on linux
 - [x] review from @matthewdahmer

### CODE REVIEW

**Comment by jzuhone** [comment]
ping @matthewdahmer @taldcroft @jeanconn @javierggt

**Comment by jeanconn** [comment]
@jzuhone Is this ready for review?  Also, per the "md5sum" conversation today and that item on the model update procedure, do you see a place on the plots where it would make sense to just stick the md5sum of the json file as run?  Thanks!

**Comment by jzuhone** [comment]
@jeanconn this isn't ready yet. We can definitely stick the md5sum somewhere. That's a good idea.

**Comment by jzuhone** [comment]
This is ready for review now, finally.

**Comment by taldcroft** [comment]
I just made a fresh ska3 and installed with `pip install .` and got this:
```
(ska3-xija) ➜  xija git:(gui_fit) xija_gui_fit --help
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
DEBUG:root:Importing gui_fit from /Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/xija/gui_fit.py
Traceback (most recent call last):
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/bin/xija_gui_fit", line 11, in <module>
    load_entry_point('xija==4.16.1.dev61+g66285f7', 'console_scripts', 'xija_gui_fit')()
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2687, in load_entry_point
    return ep.load()
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'xija.gui_fit.app'; 'xija.gui_fit' is not a package
```

**Comment by taldcroft** [comment]
Need to add `xija.gui_fit` to the `packages` list in `setup.py`.

**Comment by jzuhone** [comment]
Yes, just noticed this myself. Sorry!

**Comment by taldcroft** [comment]
And another packaging oops, I think:
```
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/bin/xija_gui_fit", line 11, in <module>
    load_entry_point('xija==4.16.1.dev61+g66285f7.d20200211', 'console_scripts', 'xija_gui_fit')()
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/xija/gui_fit/app.py", line 1174, in main
    icon = QtGui.QIcon(icon_path('app_icon'))
  File "/Users/aldcroft/miniconda3/envs/ska3-xija/lib/python3.6/site-packages/xija/gui_fit/utils.py", line 97, in icon_path
    raise RuntimeError("Icon does not exist: %s" % icon_name)
RuntimeError: Icon does not exist: app_icon.png
```

**Comment by taldcroft** [comment]
The model-update process specification for the unique identifier for the model is the MD5 sum, not sha-256.  This identifier does not need to be cryptographically secure.  :smile:

I noticed that the pop-up which displays the identifier in red does not allow selection of that value for copy/paste to a TWiki / TWG review page.  That is somewhat defeating the purpose of this very nice idea.

**Comment by jzuhone** [comment]
Sorry about the package issues--I missed these because I was always installing with `pip install -e .`

**Comment by taldcroft** [comment]
What about writing the model data out in ECSV format by default.  Then you get (in Python anyway) perfect round trip of data types including `eclipse` as a bool instead of strings of `'False'` or `'True'`.

**Comment by taldcroft** [comment]
I have made packaging mistakes so many times, that's why trying to run from an install was the first thing I tried...  And also why astropy moved to doing testing with tox that actually does an install.

**Comment by taldcroft** [comment]
Can you update the repo models files `models/dpa/dpa_spec.json` and the corresponding `acis_fp` model with new versions that include limit values?  Those serve as canonical "you can play with these" model files and would let me test that functionality in xija_gui_fit.

**Comment by jzuhone** [comment]
@taldcroft I think I've addressed everything you've mentioned here, including adding limits to the example JSON files. Let me know if you find anything else.

**Comment by matthewdahmer** [comment]
I can confirm that the bug that resulted in a crash whenever I attempted to display the histogram has been fixed! I was able to run through some of the other features on my Mac, however I won't be able to get to a start-to-finish model recalibration until next week, after the first draft of my biannual report is complete.

**Comment by jzuhone** [comment]
@matthewdahmer if you want to test this note that I have re-based it and added a commit to the "info" window which adds info about which evolve method and the solver order is being used.

**Comment by jeanconn** [comment]
I'm still planning to cut a xija release for the next Matlab Ska now.  I don't see a reason that this needs to go in.

**Comment by matthewdahmer** [comment]
@jzuhone I'm testing this now using the rebased version by attempting a refit of the ACA model with evolve_method=2 and rk4=0.

**Comment by matthewdahmer** [comment]
@jzuhone this test went much faster than I anticipated, your new gui_fit works well. I have a new ACA model that is slightly better than the current version, and functionally demonstrated that your new gui_fit can fit a new model on my Mac. Although I did not exercise every feature available, I found no problems with the features I tested. I found the histogram option you added makes comparing the current model to past models much more straightforward. The gui also feels much more responsive. Thank You!

**Comment by taldcroft** [comment]
@matthewdahmer - did you test on linux, or should we drop the requirement that GUI model fitting is tested on linux?  Personally I find things to be just so much faster on Mac that I won't go back.

**Comment by jzuhone** [comment]
Personally I do model fits on my Mac. 

@Gregg140 does them on his Linux desktop, so we could ask him to test, but that may take a while since he is on duty this week.

**Comment by matthewdahmer** [comment]
@taldcroft - I did not test on linux, and, to my knowledge, this package needs to be installed in order to test. A local installation on my Mac did not work for me when I first started testing this PR. If there is a way I can install locally on chimchim I would be happy to test it there, or if @jeanconn  can install it to a dev branch on chimchim that could also work. I currently do not have a linux environment set up where I have the appropriate admin rights to install this. 

As far as what platform I'll be using, I'll almost always be running this on my Mac, however I can foresee others wanting to run this on Linux on chimchim.

**Comment by taldcroft** [comment]
OK let's wait for @Gregg140 to do the linux testing.  He is very thorough and actually uses linux in his normal workflow, both of which are good.

**Comment by taldcroft** [comment]
This probably dropped off the radar of @Gregg140 so I went ahead and built and tested this branch on linux.  As a reminder, on our current ska3 setup it is required to build on CentOS-5 (`presto`).  With that, I did basically functionality testing and confirm everything worked as expected (including being pretty unresponsive relative to Mac laptop).

@jzuhone - can you rebase?  I'm good to merge this and would like that to happen soon since I'm doing work on xija now for the MUPS valve stuff and would like to base off this branch.  (Turns out I need to make some mods to xija because it does not currently handle telemetry data with large gaps).

**Comment by Gregg140** [comment]
Actually no it didn't fall off the radar. I tested it last week, on the 
14th  and found a problem when running on Linux.

*Problem:*

On a clean terminal my Linux desktop acis:


skadev

xija_gui_fit dpa_model_spec.json --days 365 --stop 2020:072:00:00:00.00 &
   json file attached - it's the latest cloned from dpa_check.

Look at attachment XGF_Test

I fit the 3 parameters you see checked. The plot looked unbelievably 
perfect........

But I think there's no model plot.

I zoomed in as you see in the attachment and where the vertical line is 
I should see about a 1 degree difference between the data trace and the 
model trace. I zoomed in on the location and attached that picture.

But what I think happened is that there's no model trace at all (which 
is why the fit looked so great....and here I thought
my fitting powers were awesome ;) )

Here is the terminal output which does report some issues:


acis-113: xija_gui_fit dpa_model_spec.json --days 365 --stop 
2020:072:00:00:00.00 &
[1] 2630
acis-114: Fetching msid: 1dpamzt over 2019:072:11:37:34.816 to 
2020:072:00:17:50.816
Fetching msid: sim_z over 2019:072:11:37:34.816 to 2020:072:00:17:50.816
Fetching msid: pitch over 2019:072:11:37:34.816 to 2020:072:00:17:50.816
Fetching msid: roll over 2019:072:11:37:34.816 to 2020:072:00:17:50.816
Fetching msid: aoeclips over 2019:072:11:37:34.816 to 2020:072:00:17:50.816
Reading commanded states DB over 2019:072:12:04:54.816 to 
2020:071:23:50:30.816
Fetching msid: dp_dpa_power over 2019:072:11:37:34.816 to 
2020:072:00:17:50.816
Adding plot  1dpamzt data__time
Adding plot  solarheat__dpa0 solar_heat__pitch
Adding plot  1dpamzt resid__data
INFO:fit:Fit started
INFO:fit:Calculating params:
INFO:fit:Fit statistic: 113401.5849
Process Process-1:
Traceback (most recent call last):
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/multiprocessing/process.py", 
line 249, in _bootstrap
     self.run()
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/multiprocessing/process.py", 
line 93, in run
     self._target(*self._args, **self._kwargs)
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/xija/gui_fit/fitter.py", 
line 132, in fit
     ui.fit(1)
   File "<string>", line 1, in fit
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/sherpa/ui/utils.py", 
line 7989, in fit
     res = f.fit(**kwargs)
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/sherpa/fit.py", 
line 53, in run
     result = func(fit, *args, **kwargs)
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/sherpa/fit.py", 
line 1266, in fit
     self.model.thawedparmaxes)
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/sherpa/fit.py", 
line 1007, in fit
     statargs, statkwargs)
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/sherpa/optmethods/__init__.py", 
line 97, in fit
     output = self._optfunc(cb, pars, parmins, parmaxes, **self.config)
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/sherpa/optmethods/optfcts.py", 
line 665, in neldermead
     step = 1.2*numpy.ones(x.shape, numpy.float_, numpy.isfortran(x))
   File 
"/data/acis/ska/envs/skadev/lib/python3.6/site-packages/numpy/core/numeric.py", 
line 207, in ones
     a = empty(shape, dtype, order)
ValueError: Non-string object detected for the array ordering. Please 
pass in 'C', 'F', 'A', or 'K' instead
Adding plot  1dpamzt resid__time

Most of the other functions in this PR seem to work. I did those 
experiments before this last one.

*Here is what John Z wrote about it:*

So I think what happened here is that the sherpa on skadev is not 
compatible with the NumPy on it. I tried to update sherpa but it 
wouldn’t let me.

So I just installed the new xija on acisska instead. You can try running 
on there and you should not see the same error--I just tested this.


Gregg

**Comment by taldcroft** [comment]
@Gregg140 - ok.  Please be sure to use GitHub for all traffic related to Ska3 code development and review.  The rest of the community will not be aware of off-thread conversations.

**Comment by jzuhone** [comment]
@Gregg140 Any chance you could check this today, using the `acisska` setup? I know you're on-duty. I was able to reproduce your steps without the crash.

**Comment by taldcroft** [comment]
@jzuhone - as you discovered, it is not a good idea to test in a dev environment that does not match production, esp. with regards to numpy version.
```
(skadev) kady$ conda list | grep numpy
numpy                     1.18.1                    <pip>
numpy                     1.12.1                   py36_0  
```
For independent package testing I have been creating a dedicated environment that is named to be easily recognizable e.g. `ska3-test-gui-fit`.  So make a fresh env installing `ska3-flight`, then `conda uninstall --force xija`, `pip install .` from your repo, and then remove the whole environment later.  At least for me having a generic dev environment gets confusing because I quickly forget what was in there.

**Comment by taldcroft** [comment]
I did the rebase and fixed the conflict in `setup.py`.  Local testing including an install test to a fresh ska3 on Mac and confirming basic functionality.  (Mostly if `xija_gui_fit` starts up then from the perspective of the rebase of setup.py that implies success).

I also pushed up a branch `gui_fit_pre_rebase` for reference in case there is a problem.

Going to merge now.  This won't be tagged for release until @Gregg140 documents successful testing here, but given that @jzuhone was able to replicate the problem and then provide a solution that worked for him, it seems fine to merge to master now.

@jzuhone - thanks again for a fantastic update.  I'm pushing on this because I really want to use it now!

**Comment by taldcroft** [comment]
:tada: 🚀

**Comment by jzuhone** [comment]
sorry @taldcroft I rebased it here but must have forgotten to push it up. brain fried with all of this going on and watching a 3-year-old...

**Comment by taldcroft** [comment]
No worries, easy rebase.  I was a little concerned about force pushing to your branch (and hope you don't mind) but it all seems to have worked.

**Comment by Gregg140** [comment]
Ran it pretty thoroughly using Linux and it looks fine to me.  Lots of new, good features.

**Comment by jzuhone** [comment]
@jeanconn @taldcroft ok, I think that means we are ready to tag a release! Thanks @Gregg140!

**Pull request merged**
